### ISSUE TITLE
Please advice on how to use the library with type=module

### ISSUE THREAD

**Issue by akefirad** [gcanti/fp-ts#1854]
I'm not sure if it's a bug or just a lack of documentation. I'm trying to use the library in a `module` project:
```jsonc
// package.json
{
  "name": "fp-ts-esm",
  "type": "module",
  "scripts": {
    "run": "ts-node ./index.ts"
  },
  "dependencies": {
    "fp-ts": "^2.14.0",
    "typescript": "^5.0.4"
  },
  "devDependencies": {
    "@tsconfig/node18": "^1.0.0",
    "@types/node": "^18.0.0",
    "ts-node": "^10.9.1"
  }
}
```
```jsonc
// tsconfig.json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "@tsconfig/node18/tsconfig.json",
  "display": "Node 18",
  "ts-node": {
    "esm": true
  },
  "compilerOptions": {
    "module": "ES2022"
  },
  "include": ["**/*.ts"]
}
```
```ts
// index.ts
import { range } from "fp-ts/NonEmptyArray";

const arr = range(1, 10);
console.log(arr); // [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
```
This fails with the famous `CustomError: ERR_UNSUPPORTED_DIR_IMPORT` error:
```
/Users/rad/temp/fp-ts-esm/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:362
    const err = new ERR_UNSUPPORTED_DIR_IMPORT(path, fileURLToPath(base));
                ^
CustomError: ERR_UNSUPPORTED_DIR_IMPORT /Users/rad/temp/fp-ts-esm/node_modules/fp-ts/NonEmptyArray /Users/rad/temp/fp-ts-esm/index.ts
    at finalizeResolution (/Users/rad/temp/fp-ts-esm/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:362:17)
    at moduleResolve (/Users/rad/temp/fp-ts-esm/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/Users/rad/temp/fp-ts-esm/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /Users/rad/temp/fp-ts-esm/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/Users/rad/temp/fp-ts-esm/node_modules/ts-node/src/esm.ts:168:34)
    at /Users/rad/temp/fp-ts-esm/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/Users/rad/temp/fp-ts-esm/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/Users/rad/temp/fp-ts-esm/node_modules/ts-node/src/esm.ts:197:12)
    at resolve (/Users/rad/temp/fp-ts-esm/node_modules/ts-node/src/child/child-loader.ts:15:39)
    at nextResolve (node:internal/modules/esm/loader:163:28) {
  url: 'file:///Users/rad/temp/fp-ts-esm/node_modules/fp-ts/NonEmptyArray'
}
```
When I change the import to `"fp-ts/lib/NonEmptyArray.js"` everything works just fine. Is that the way the library should be used in a module project? Or am I missing something. Thanks.

**Comment by akefirad** [comment]
I see. So that’s the way to go for the time being. Thanks.
