### ISSUE TITLE
Issue on concat for Option<NonEmptyArray>

### ISSUE THREAD

**Issue by MaximeRDY** [gcanti/fp-ts#744]
Hello, 

I think I found a bug but not sure if it's related to your project or typescript or js

I've tried this code on NonEmptyArraySpec:
```ts
it('should not raise', () => {
    const x = new NonEmptyArray(1, [2])
    const optY = some(new NonEmptyArray(3, [4]))
    assert.deepStrictEqual(optY.fold(x, x.concat).toArray(), [1, 2, 3, 4])
  })
```

When I run it, it produce this stack trace :
```js
    TypeError: Cannot read property 'concatArray' of undefined
      at NonEmptyArray.concat (src/NonEmptyArray.ts:5274:21)
      at Some.fold (src/Option.ts:6167:16)
      at Object.<anonymous> (test/NonEmptyArray.ts:26:30)
```

To fix it, I need to do this:
```ts
it('should not raise', () => {
    const x = new NonEmptyArray(1, [2])
    const optY = some(new NonEmptyArray(3, [4]))
    assert.deepStrictEqual(optY.fold(x, y => x.concat(y)).toArray(), [1, 2, 3, 4])
  })
```

Do you have any idea, why ? 

Thanks a lot

**Comment by gcanti** [comment]
@MaximeRDY that's expected, `concat` is a method
