### ISSUE TITLE
[Task] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mxth** [gcanti/fp-ts#983]
### Current Behavior
`array.sequence` a large number of `Task` (>5000 approx) would throw `RangeError`

### Expected behavior
Not to throw `RangeError`

### Reproducible example

```typescript
import { array, map, range } from 'fp-ts/lib/Array'
import { pipe } from 'fp-ts/lib/pipeable'
import { task } from 'fp-ts/lib/Task'

pipe(
  range(1, 6000),
  map(a => () => Promise.resolve(a)),
  array.sequence(task),
)()
```
would throw
```
 RangeError: Maximum call stack size exceeded

      at ../../node_modules/fp-ts/lib/Task.js:106:37
      at ma (../../node_modules/fp-ts/lib/Task.js:104:57)
      at mab (../../node_modules/fp-ts/lib/Task.js:106:71)
      at ma (../../node_modules/fp-ts/lib/Task.js:104:57)
      at mab (../../node_modules/fp-ts/lib/Task.js:106:71)
      at ma (../../node_modules/fp-ts/lib/Task.js:104:57)
      at mab (../../node_modules/fp-ts/lib/Task.js:106:71)
      at ma (../../node_modules/fp-ts/lib/Task.js:104:57)
      at mab (../../node_modules/fp-ts/lib/Task.js:106:71)
      at ma (../../node_modules/fp-ts/lib/Task.js:104:57)
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.0.5       |
| TypeScript |    3.5.3        |

**Comment by giogonzo** [comment]
Changing the implementation of `task.ap` to:

```ts
ap: (mab, ma) => () => Promise.resolve().then(() => Promise.all([mab(), ma()]).then(([f, a]) => f(a)))
```

seems to "fix" this
